name: Generate Contribution Animations

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia Ã  meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # ğŸŸ¡ Gera Pac-Man
      - name: Generate Pac-Man Graph
        uses: Platane/snk@v3
        with:
          github_user_name: MateusFego
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg

      # ğŸ Gera Snake Animation
      - name: Generate Snake Graph
        uses: Platane/snk@v3
        with:
          github_user_name: MateusFego
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg

      # ğŸ”¥ Faz o push para o branch output
      - name: Push Generated Files
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
